### ISSUE TITLE
極端に短い時間を設定して EmuAPU でエミュレーションを実行すると、DSP のエミュレーションが(一部 ?)実行されない。

### ISSUE THREAD

**Issue by GodGnilda** [dgrfactory/spcplay#17]
# 不具合の内容

極端に短い時間を設定して EmuAPU でエミュレーションを続けると、DSP のエミュレーションが(一部 ?)実行されない。

# 実行環境

Windows 8.1 Update1
SNESAPU v2.18.1

# 再現手順

1. len に SPC700 の命令を一つ分など極端に短い時間を設定し、EmuAPU を連続で実行する。

2. キーオンされて時間が経過しても *Voice::bCur, DSPVoice::envx, DSPVoice::outx の値が変化しない。

# その他

- t64Cnt は増加し続けているので DSP.asm の CatchUp で即 .Done とはならないはず ?

#  画像

<details>
<summary>約 1 秒実行</summary>
<img src="https://user-images.githubusercontent.com/72546447/95654460-13e9d680-0b3b-11eb-92f9-fda049ed4070.png" title="1 秒シーク">
<img src="https://user-images.githubusercontent.com/72546447/95654466-1a784e00-0b3b-11eb-8c00-5b949048bb29.png" title="1 命令ずつ実行">

- キーオン設定後約 20Ts でRead の値が Addr の値に変化しますが、以降は変化しません。
</details>

**Comment by dgrfactory** [comment]
@GodGnilda さん
このたびは不具合をご報告いただきまして、誠にありがとうございます。

本件不具合につきまして、事象の再現ができましたので、 https://github.com/dgrfactory/spcplay/commit/66c065a14a11ce6634ea59d11b32dd4266827d62 で修正いたしました。
修正を含む SNESAPU.DLL を添付いたしますので、どうぞお試しください。

どうぞ、よろしくお願いいたします。

[snesapu-2.18.2.6862-b1.zip](https://github.com/dgrfactory/spcplay/files/5408185/snesapu-2.18.2.6862-b1.zip)

**Comment by GodGnilda** [comment]
うっかり修正をせずに命令サイクル未満で 2 回 EmuAPU を実行した場合は Pitch の値が 0x1000 以外の場合は若干小さな値になっていましたが、1 回で命令サイクル分実行した場合は Read,EX,OX の値が SEEKAPU で実行した場合と同じ値になることを確認いたしました。
ご修正いただきありがとうございます。
![実行ファイルを修正後に EmuAPU を 1 秒分実行](https://i.imgur.com/c6n6uN6.png)
