### ISSUE TITLE
必要最小限の APU サイクルで EmuAPU を利用し SPC700 の命令を一つ分実行すると、GetSPCRegs の PC の値が想定した値と異なる値になる。

### ISSUE THREAD

**Issue by GodGnilda** [dgrfactory/spcplay#18]
# 不具合の内容

必要最小限の APU サイクルで EmuAPU を利用し SPC700 の命令を一つ分実行すると、GetSPCRegs の PC の値が想定した値と異なる値になる。

# 実行環境

Windows 8.1 Update1
SNESAPU v2.18.1

# 再現手順

1. LoadSPCFile で SPC ファイルを読み込む。

2. GetSPCRegs で PC の値を取得する。

3. PC の指す APU メモリの値を取得し、次の命令の実行に必要な APU サイクル数 [*1] と、実行後の PC の値 [*2] を計算する。

4. EmuAPU (len = [*1]) を実行する。

5. GetSPCRegs で PC の値を取得し、[*2] の値と比較すると異なる値である。

# 回避策

再現手順 4 で EmuAPU (len = [*1] - 1) と EmuAPU (len = 1) を実行する。

ただし時間が短すぎるためか、 DSP のエミュレーションは実行されないようである(#17)。

# 画像
<img src="https://user-images.githubusercontent.com/72546447/95480139-838a8500-09c6-11eb-9f09-365f6815fe0a.png" title="120 APU サイクル分だけ実行">

**Comment by dgrfactory** [comment]
@GodGnilda さん
このたびは不具合をご報告いただきまして、誠にありがとうございます。

本件不具合につきまして、事象の再現ができましたので、 https://github.com/dgrfactory/spcplay/commit/66c065a14a11ce6634ea59d11b32dd4266827d62 で修正いたしました。
修正を含む SNESAPU.DLL を添付いたしますので、どうぞお試しください。

どうぞ、よろしくお願いいたします。

[snesapu-2.18.2.6862-b1.zip](https://github.com/dgrfactory/spcplay/files/5408185/snesapu-2.18.2.6862-b1.zip)

**Comment by GodGnilda** [comment]
一度の EmuAPU 実行で PC の値が想定した値と同じ値になることを確認いたしました。
ご修正いただきありがとうございます。
