### ISSUE TITLE
SNESAPUCallbackで設定するコールバック関数 effect = CBE_DSPREG の仕様がサイトの説明と異なる。

### ISSUE THREAD

**Issue by GodGnilda** [dgrfactory/spcplay#21]
# 不具合の内容
SNESAPUCallbackProc で設定するコールバック関数 effect = CBE_DSPREG の仕様が @dgrfactory 様のサイトの説明では
> addr | DSP レジスタのアドレス (0x00～0x7F)

となっていますが、実際はアドレスの範囲チェック前に呼び出されるため 0x80 - 0xFF の値を指定可能になっています。
想定していないアプリは誤動作や異常終了する可能性があります。

![DSP レジスタアドレス 0x80 への書き込み要求](https://user-images.githubusercontent.com/72546447/97001313-21f41a00-1573-11eb-8518-87191b93dfe3.png)

**Comment by dgrfactory** [comment]
@GodGnilda さん
再度、不具合をご報告いただきまして、誠にありがとうございます。
事象を確認することができましたので、リビジョン https://github.com/dgrfactory/spcplay/commit/983d93e9ea6d56445e5641ad88c7cb3a1973964d にて修正いたしました。

修正内容：
* 0x80 以上の範囲外アドレスが指定された場合、DSP には影響ないことを考慮して、コールバックも行わないように修正。
* アドレスの他、書き換えようとしている DSP 値についても、上位 24bit は 0 クリアする（有効範囲下位 8bit）ように修正。

本修正を含む SNESAPU.DLL は、以下よりダウンロード可能です。
[snesapu-v2.18.2.7141.zip](https://github.com/dgrfactory/spcplay/files/5432869/snesapu-v2.18.2.7141.zip)

どうぞ、よろしくお願いいたします。

**Comment by GodGnilda** [comment]
範囲外のアドレスが指定された場合にコールバックが行われないことと、value の上位  24 ビットが 0 クリアされていることを確認いたしました。
![value の上位  24 ビットが 0 クリアされている](https://user-images.githubusercontent.com/72546447/97102094-03626000-16e6-11eb-88c5-6176b512402f.png)

ご修正いただきありがとうございます。
