### ISSUE TITLE
Latest version seems to break with Asterix soundtrack

### ISSUE THREAD

**Issue by VitorVilela7** [dgrfactory/spcplay#25]
When you load any song from Asterix soundtrack, the note appears to be cut off as soon attack phrase is done. Envelope is cut to 00.

Probably, something is wrong on GAIN emulation.

**Comment by VitorVilela7** [comment]
Version is v2.18.3

**Comment by dgrfactory** [comment]
Hi, @VitorVilela7
Thank you for reporting the issue.

I have confirmed this reported issue, and released a fixed version.
https://github.com/dgrfactory/spcplay/releases/tag/2.18.4.7333

**Comment by VitorVilela7** [comment]
It is now working perfectly, thank you for the quick update!

**Comment by dgrfactory** [comment]
Released.
https://github.com/dgrfactory/spcplay/releases/tag/2.18.4.7379
