### ISSUE TITLE
Suggestion: ability to slow down SPCs down to 1% instead of 25% and speed them up to 800% instead of 400%

### ISSUE THREAD

**Issue by Anas13303** [dgrfactory/spcplay#26]
The title should be self-explanatory. By adding this useful feature, we might be able to, to say, more precisely catch the values of strong frequency-based effects (such as tremolo and pitch bends) in SPCs for which there's no dedicated engine documentation or tools to extract the MML data from or see if there are very slight tick desyncs which cannot be perceived even when slowed down to 25%. Thanks in advance!

**Comment by dgrfactory** [comment]
Hi, @Anas13303
Thank you for your request.

Is the final goal of this request to make a music score?

As you may already know, if you want to store SPC in midi, you can consider using "spc2midi."
This software also recreating a pitch bend.
You will be able to see the detailed pitch changes from midi file you have created.

If you simply want to see the pitch value in real time, I will consider adding an option.

Thanks

**Comment by Anas13303** [comment]
> Hi, @Anas13303
> Thank you for your request.
> 
> Is the final goal of this request to make a music score?
> 
> As you may already know, if you want to store SPC in midi, you can consider using "spc2midi."
> This software also recreating a pitch bend.
> You will be able to see the detailed pitch changes from midi file you have created.
> 
> If you simply want to see the pitch value in real time, I will consider adding an option.
> 
> Thanks

Yeah, I simply want to see the pitch and volume values and whatnot in real time.

**Comment by dgrfactory** [comment]
@Anas13303 
Thank you for waiting.
I have added 1%, 5%, 10%, 20%, 500%, 600%,700%, and 800% to "Speed" menu of "Settings", so please try it.
https://github.com/dgrfactory/spcplay/releases/tag/2.18.4.7350

**Comment by dgrfactory** [comment]
Released.
https://github.com/dgrfactory/spcplay/releases/tag/2.18.4.7379
