### ISSUE TITLE
Volume issue

### ISSUE THREAD

**Issue by LucianoTheWindowsFan** [dgrfactory/spcplay#28]
I used the latest pre-release build of SPCplay and some songs (such as the Dr. Mario config theme from _Tetris & Dr. Mario_, as well as the title themes from _Extra Innings_ and _Smash Tennis_). This issue was present on older builds and I'm surprised how it wasn't fixed in years.

**Comment by dgrfactory** [comment]
Hi, @LucianoTheWindowsFan

I compared the sound with actual machine (SHVC-SOUND), but I could not find any clear difference.
Specifically, what kind of problems were there?

If sound stops on the way, the volume may be too high.
In this case, select 100% in "Volume" of "Settings."

**Comment by LucianoTheWindowsFan** [comment]
I played them at 400% and it won't play. I wish there was an option to disable ear-protection.

**Comment by dgrfactory** [comment]
@LucianoTheWindowsFan
An option to unprotect exists, although hidden ...
Please see a comment on past issue. https://github.com/dgrfactory/spcplay/issues/23#issuecomment-775953482
