### ISSUE TITLE
3 spcs from Radical Entertainment games crash on the beta release

### ISSUE THREAD

**Issue by BlinxTheWinx** [dgrfactory/spcplay#29]
League Champs from Brett Hull Hockey, Playoff Standings from Brett Hull Hockey '95 and Sucess! from Speed Racer in My Most Dangerous Adventures crash on the last build of spcplay.

**Comment by dgrfactory** [comment]
Hi, @BlinxTheWinx
Thank you for reporting the issue.

I checked the bug and released a fixed version.
This issue is due to a previously addressed #25 fix mistake...
https://github.com/dgrfactory/spcplay/releases/tag/2.18.4.7364

**Comment by dgrfactory** [comment]
Released.
https://github.com/dgrfactory/spcplay/releases/tag/2.18.4.7379
