### ISSUE TITLE
[質問] LadpX または LadpY マクロを使用するオペコードのポインタ取得処理について

### ISSUE THREAD

**Issue by GodGnilda** [dgrfactory/spcplay#30]
先日は 16 ビットデータアクセスの件でご修正いただき、誠にありがとうございます。
#27 の @dgrfactory 様の検証内容に関する質問内容でございますこと心より謝罪申し上げます。

MOVW YA,dp などのオペランドに dp を使用する 16 ビットデータを処理する命令ではダイレクトページを超えないメモリ参照が行われるのを確認いたしましたが、MOV  A,[dp+X] などのポインタ値を取得する命令の場合ポインタ値取得時にダイレクトページを超えるのが正しい処理でよろしいでしょうか。

お手数をおかけしますが、ご回答いただけますと幸いです。

<details>
<summary>他のプロセッサやエミュレータの動作</summary>

1. RP2A03 (d,x) Indexed indirect https://wiki.nesdev.com/w/index.php/CPU_addressing_modes
1. bsnes 64d4844 (May 26, 2021)・snes9x 9398d21 (May 27, 2021)・Mesen-S 89199f2 (Jul 9, 2020) はポインタ値を取得する命令もダイレクトページを超えないメモリ参照
	- [E7F7.txt](https://github.com/dgrfactory/spcplay/files/6647572/E7F7.txt)
1. https://ux.getuploader.com/gnilda/download/25 (ダウンロードパスワード : spc) 適用後の ROM を snes9x 1.53 で実行 (オペコード $E7 が snesapu.dll と同じ仕様)
	- ポインタ値取得時にダイレクトページを超えるメモリ参照が行われる場合は、シーケンスコマンド $E1 オクターブ + 1 と $E2 オクターブ - 1 が無効になります。
	- ![20210612](https://user-images.githubusercontent.com/72546447/121879412-c5cf4780-cd47-11eb-98bb-cb6415bc53b6.png)
 	- https://user-images.githubusercontent.com/72546447/121877654-cc5cbf80-cd45-11eb-94d0-8dc1416e7795.mp4
</details>

**Comment by dgrfactory** [comment]
@GodGnilda さん
お問い合わせいただき、ありがとうございます。

> MOV A,[dp+X] などのポインタ値を取得する命令の場合ポインタ値取得時にダイレクトページを超えるのが正しい処理でよろしいでしょうか。

いいえ、
[dp+X] のポインタは、ダイレクトページの範囲内で（ダイレクトページを超えず）ポインタ処理される想定でございます。
例えば P フラグがオン（dp = $01xx）、`MOV A,[$30+X]` で X = $CF のとき、参照アドレスは `[$0200][$01FF]` ではなく `[$0100][$01FF]` となるのが正しい動作との認識です。

前回同様、ダイレクトページ内の 16bit の取り扱い（今回は LadpX, LadpY マクロ）に問題があるようです。
恐れ入りますが、修正までいましばらくお待ちいただきますよう、お願いいたします。

**Comment by dgrfactory** [comment]
@GodGnilda さん
このたびは不具合をご報告いただきまして、誠にありがとうございます。
LadpX, LadpY マクロにおいて、16bit アドレス（`[dp+X]` および `[dp]`）の計算中にダイレクトページ境界を超える不具合を確認いたしました。

本不具合は、以下リリースにおいて修正しております。
 たいへんお手数ですが、ご確認いただきますようお願い申し上げます。
https://github.com/dgrfactory/spcplay/releases/tag/2.18.4.7375

**Comment by GodGnilda** [comment]
@dgrfactory 様

早々にご回答いただき大変恐れ入ります。
ダイレクトページを超えないのが正しい動作なのですね。
https://github.com/dgrfactory/spcplay/issues/27#issuecomment-846541188 の動作変更の一覧にございませんでしたので、ページを超えるのが仕様と勝手な思い込みをいたしまして、大変お手数をおかけしました。深くお詫び申し上げます。
***
最新版を以下のオペコードで動作確認いたしました。
1. LadpX マクロを使用するオペコードが 16 ビットアドレス取得でダイレクトページ境界を超えないことを確認いたしました。
	```
	$E7  MOV      A,[dp+X]
	```
2. LadpY  マクロを使用するオペコードが 16 ビットアドレス取得でダイレクトページ境界を超えないことを確認いたしました。
	```
	$F7  MOV      A,[dp]+Y
	```

ご修正いただき誠にありがとうございます。

**Comment by dgrfactory** [comment]
@GodGnilda さん
早速、動作をご確認いただきまして、ありがとうございます。
以前の修正に不備があり、申し訳ありません。

bsnes は各チップの動作をナノ秒単位でエミュレーションしており、
動作に違いがありました場合、bsnes が実機に最も近い挙動かと思われます。
実際、正しく演奏されない事象が確認された場合には、bsnes のソースコードを参照しております。

改めまして、このたびはご報告いただきまして、感謝いたします。
また何かありましたら、どうぞよろしくお願い申し上げます。

**Comment by dgrfactory** [comment]
修正版がリリースされました。 クローズします。
https://github.com/dgrfactory/spcplay/releases/tag/2.18.4.7379
