### ISSUE TITLE
SPC700.asm の ResetSPC で ARAM $00E1 の値が 0x80 で上書きされる。

### ISSUE THREAD

**Issue by GodGnilda** [dgrfactory/spcplay#31]
ResetSPC の **Enable ROM reading** のコメントがある行の命令 _Mov byte [EAX-0Fh],80h_ で ARAM $00E1 の値が 0xFF から 0x80 に上書きされるようです。

#**Timer status is preserved, other bits are reset** のコメントがある行の次の行の命令 _Or byte [EAX+1],80h_ で既に IPL ROM 読み込みフラグがオンに設定されているようです。

**Comment by dgrfactory** [comment]
@GodGnilda さん
このたびは、不具合をご報告いただきまして、誠にありがとうございます。

以下リリースにおいて修正を行いました。
たいへんお手数ですが、ご確認いただきますようお願い申し上げます。
https://github.com/dgrfactory/spcplay/releases/tag/2.18.4.7375

SNESAPU v3.0 から初期化処理の移植時、古い SNESAPU v2.0 のコードの削除忘れによるものでした。
`Mov byte [EAX-0Fh],80h` は `EAX = $100` であることが前提のコードとなっており、`EAX = $F0` を前提とした新しいコードである `Or byte [EAX+1],80h` と処理の意図が重複するため、古い方のコードを削除いたしました。

**Comment by GodGnilda** [comment]
@dgrfactory 様

初期化直後の ARAM $00E1 の値が 0xFF であることを確認いたしました。

![20210615_ResetSPC](https://user-images.githubusercontent.com/72546447/122062156-1c14b700-ce2a-11eb-8ce8-0e164082798c.png)

ご修正いただきありがとうございます。

**Comment by dgrfactory** [comment]
@GodGnilda さん
早速ご確認いただきまして、ありがとうございます。
このたびはご迷惑おかけし、申し訳ありません。

**Comment by dgrfactory** [comment]
修正版がリリースされました。 クローズします。
https://github.com/dgrfactory/spcplay/releases/tag/2.18.4.7379
