### ISSUE TITLE
Initializing application is failed. (ERROR 119)

### ISSUE THREAD

**Issue by HopkinsFBI** [dgrfactory/spcplay#32]
When trying to build the spcplay.exe frontend it seems to compile ok but I get the following error every time I run the resulting exe "Initializing application is failed. (ERROR 119)"

Is this related to the version of dcc32 used? Can you share more information on how to set up a working dev environment for this project? You mention Delphi6 UP2 RTL3 in the readme, but I'm not certain where to obtain this software or how to get it running on a modern system.

**Comment by dgrfactory** [comment]
Hi, @HopkinsFBI
Thank you for reporting the issue.

ERROR 119 is a signature error.
This error occurs if SNES SPC700 Player is not an official release binary.
If you build from source code, there will be no official signature, but you should be able to run by commenting out the signature check.

```diff
- if not longbool(result) then result := CheckImageHash(sEXEPath, 10);
+ // if not longbool(result) then result := CheckImageHash(sEXEPath, 10);
```

**Comment by HopkinsFBI** [comment]
It looks like commenting out that check allows it to get farther, but now I'm getting "Initializing SNESAPU.DLL is failed. (ERROR 103)"

I've got a copy of the SNESAPU.DLL from the latest release in the same directory, so not sure why it is erroring out

**Comment by dgrfactory** [comment]
@HopkinsFBI

ERROR 103 is a SNESAPU.DLL compatibility check error.
Probably, the versions of SPCPLAY.EXE and SNESAPU.DLL do not match exactly.
Please check version numbers of SPCPLAY.EXE and SNESAPU.DLL.

**Comment by HopkinsFBI** [comment]
Thanks, using the v2.18.3 (build 7258) of the SNESAPU.DLL finally allows the version I compiled to run!
