### ISSUE TITLE
SETP ($40) を実行すると PSW の I フラグに 0 が設定される。

### ISSUE THREAD

**Issue by GodGnilda** [dgrfactory/spcplay#33]
平素より、大変お世話になっております。

SETP ($40) を実行いたしますと、PSW の P フラグに 1 が、更に I フラグに 0 が設定されるのを確認いたしました。

#動作は問題ございませんが、RETI ($7F) の PSW に関するコメントは実際の動作と異なるようです。 (I = 1, 他 = ?)

**Comment by dgrfactory** [comment]
@GodGnilda さん
不具合のご報告をいただきまして、誠にありがとうございます。

下記のリリースで修正いたしました。
たいへんお手数をおかけいたしますが、ご確認いただきますようお願い申し上げます。
https://github.com/dgrfactory/spcplay/releases/tag/2.18.4.7379

１．
SETP ($40) 命令において、意図せず I フラグに 0 がセットされる事象を確認いたしました。
こちらは本家 SNESAPU からある不具合の模様で、最新バージョン v3.0 でも修正されておりませんでした。
SNESAPU がなぜこのような動作となっているかは不明ですが、SPC700 仕様書、及び、snes9x・bsnes のソースコードを確認し、I フラグの 0 セットは不要との判断をいたしました。

２．
RETI ($7F) のコメントにおいて、I が 1 と記述されていることを確認いたしました。
こちらも本家 SNESAPU からの誤りのようでしたので、コメントの I 部分を ? に変更いたしました。

**Comment by GodGnilda** [comment]
@dgrfactory 様

今回は PSW の復帰時間を短くする方法などを確認していましたところ、偶然発見いたしました。

最新版で SETP を実行しても PSW の I フラグが変化しないことを確認いたしました。
ご修正いただきありがとうございます。

**Comment by dgrfactory** [comment]
修正版がリリースされました。 クローズします。
https://github.com/dgrfactory/spcplay/releases/tag/2.18.4.7379
