### ISSUE TITLE
機能追加要望 [Script700] サウンドドライバが特定の入力ポートを読み込むまで待機するコマンドが欲しい。

### ISSUE THREAD

**Issue by GodGnilda** [dgrfactory/spcplay#34]
### 目的
- 転送時間を短くするために、スクリプトで反映させた入力ポートの値をすべて読み込む前に出力ポート o0 に値を書き込むサウンドドライバの待ち時間を短縮したい。
- 初回・2 回目以降で待ち時間が変化する場合でもコマンド一つで解決できるようにしてコード量を削減したい。

### コマンド
`特定のポートを読み込むまで待機 [入力ポート]`

サウンドドライバは bsnes などエミュレータでは正しく演奏されることを確認済です。
ご検討よろしくお願いいたします。

**Comment by dgrfactory** [comment]
@GodGnilda さん
平素よりお世話になっております。
ご要望をいただき、誠にありがとうございます。

現在、以下のコマンド体系で実装・試験中です。
今しばらくお待ちくださいませ。

* SPC700 が特定の I/O ポートを読み込むまで待機：
  【構文】 `wi [PORT]`
  【実装例】ポート0の値が読み込まれるまで待機： `wi 0`
  【パラメータ】[パラメータグループ3](https://dgrfactory.jp/spcplay/script700.html#script_param3) から選択

  * 備考
    * `CMP[0]` に待機したサイクル数（2.048MHz ベース）が書き込まれます（[`f` コマンド](https://dgrfactory.jp/spcplay/script700.html#script_flush) と同様）
    * サイクル数は `m #? w0` などで取り出すことができます。

* SPC700 が特定の I/O ポートに書き込むまで待機：
  【構文】 `wo [PORT]`
  【実装例】ポート0に値が書き込まれるまで待機： `wo 0`
  【パラメータ】[パラメータグループ3](https://dgrfactory.jp/spcplay/script700.html#script_param3) から選択

  * 備考
    * `CMP[0]` に待機したサイクル数（2.048MHz ベース）が書き込まれます（[`f` コマンド](https://dgrfactory.jp/spcplay/script700.html#script_flush) と同様）
    * サイクル数は `m #? w0` などで取り出すことができます。

上記仕様にて何等か不都合がございましたら、ご返信いただけますと幸いです。
どうぞ、よろしくお願い申し上げます。

**Comment by GodGnilda** [comment]
@dgrfactory 様
ご提案いただきました内容で、問題ございません。
引き続きよろしくお願いいたします。

**Comment by dgrfactory** [comment]
@GodGnilda さん
ご返信いただき、ありがとうございます。
下記リリースにて対応いたしました。 どうぞお試しください。
https://github.com/dgrfactory/spcplay/releases/tag/2.19.0.7471

**Comment by GodGnilda** [comment]
@dgrfactory 様
wi および wo コマンドを使用して僅かなコード量で高速に転送可能であることを確認いたしました。
お忙しいところ、ご対応頂き誠にありがとうございます。

**Comment by dgrfactory** [comment]
@GodGnilda さん
早速、動作をご確認いただきましてありがとうございます。
本 issue はクローズいたします。
今後とも、どうぞよろしくお願いいたします。
