### ISSUE TITLE
機能追加要望 [Script700] 対応プレイヤーにコールバックを利用してブレークポイントを設定するコマンドが欲しい。

### ISSUE THREAD

**Issue by GodGnilda** [dgrfactory/spcplay#35]
### 目的
- サウンドドライバのファンクションを利用して演奏に必要なデータを転送した状態のスナップショットを保存するために、Script700 のコマンドで SPC700 の動作を停止させたい。

### スナップショット作成手順
- Script700 でデータをすべて転送する。
- 転送終了時に Script700 のコマンドでプレイヤーのコールバック関数を利用してブレークポイントを設定する。
- SPC700 の動作が停止している状態のスナップショットを保存する。

### コマンド
`ブレークポイント設定コマンド [ブレークポイントを設定するアドレス]`

実行ファイルと違いスクリプトであれば spcplay.exe (と転送用のデータのみ)で実行可能ですので、ハードルが低いかなと…
以上です。ご検討よろしくお願いいたします。
<hr>
コマンドを修正しました。

**Comment by dgrfactory** [comment]
@GodGnilda さん
平素よりお世話になっております。
ご要望をいただき、誠にありがとうございます。

現在、以下のコマンド体系で実装・試験中です。
今しばらくお待ちくださいませ。

* 特定のプログラムカウンタで SPC700/DSP の動作を停止：
  【構文】 `bp [ADDR]`
  【実装例】PC が 0x1234 に到達したとき停止： `bp #$1234`
  【パラメータ】[パラメータグループ3](https://dgrfactory.jp/spcplay/script700.html#script_param3) から選択

  * 備考
    * spccmd.exe の [ブレイクコマンド](https://dgrfactory.jp/spcplay/spccmd.html#options_breakpoint) における SPC_HALT＋DSP_PAUSE と同様の動作を行います。
    * Script700 ではブレイクポイントを解除できませんが、spccmd.exe の -bp コマンドで、解除ができます。
    * 演奏を最初から開始した場合、spccmd.exe で設定したブレイクポイントの設定は保持されますが、Script700 経由で設定したブレイクポイントは解除されます。

上記仕様にて何等か不都合がございましたら、ご返信いただけますと幸いです。
どうぞ、よろしくお願い申し上げます。

**Comment by GodGnilda** [comment]
@dgrfactory 様
ご提案いただきました内容で、問題ございません。
引き続きよろしくお願いいたします。

**Comment by dgrfactory** [comment]
@GodGnilda さん
ご返信いただき、ありがとうございます。
下記リリースにて対応いたしました。 どうぞお試しください。
https://github.com/dgrfactory/spcplay/releases/tag/2.19.0.7471

**Comment by GodGnilda** [comment]
@dgrfactory 様
bp コマンドを使用してブレークポイントを設定可能であることを確認いたしました。

- wi を使用するお行儀の悪いサウンドドライバ
![wi を使用して転送](https://user-images.githubusercontent.com/72546447/134179535-112bda25-bf30-42b5-9dee-13b2288666b5.png)

- wo 0 を使用して転送する普通のサウンドドライバ
![wo 0 を使用して転送](https://user-images.githubusercontent.com/72546447/134179739-e510271c-a400-433e-a25f-ddb1c4455f54.png)

お忙しいところ、ご対応頂き誠にありがとうございます。

**Comment by dgrfactory** [comment]
@GodGnilda さん
早速、動作をご確認いただきましてありがとうございます。
本 issue はクローズいたします。
今後とも、どうぞよろしくお願いいたします。
