### ISSUE TITLE
Issues with transitions from decay to sustain

### ISSUE THREAD

**Issue by brickblock369** [dgrfactory/spcplay#38]
In the emulators that I tested with, while the note is in the "decay" mode, if the ADSR's sustain value changes mid-note and its changed sustain value is higher (which causes less decay time), the decay time still has to decay to its _initial_ sustain value, despite the higher sustain value that causes less decay time.

However, in SPCPlay, when the sustain value gets higher mid-note while the note is decaying, it skips the decay and goes straight into sustain/release, which is inaccurate.

**Comment by dgrfactory** [comment]
Hi, @brickblock369
Thank you for reporting the issue.

I will investigate, so if you have an SPC file that occurred this bug, please attach it here or reply a link for download.

**Comment by brickblock369** [comment]
[Test SPCs.zip](https://github.com/dgrfactory/spcplay/files/7592688/Test.SPCs.zip)

By the way I've confirmed with someone that it happens on actual hardware too, via SD2SNES.

**Comment by dgrfactory** [comment]
@brickblock369
I have confirmed this reported issue, and released a fixed version.
Please try it.
https://github.com/dgrfactory/spcplay/releases/tag/2.19.1.7537

**Comment by brickblock369** [comment]
Yes, that's how it works! Thanks!
