### ISSUE TITLE
[spcplay.exe] 名前を付けて保存のダイアログでファイルの種類にかかわらず保存ファイル名に ファイル名.spc が設定される場合がある。

### ISSUE THREAD

**Issue by GodGnilda** [dgrfactory/spcplay#40]
ファイル保存時のファイルの選択ダイアログのファイル名には、最後に読み込んだ SPC ファイルのファイル名またはタイトルが保存するファイル名として設定されますが、タイトルが存在せず かつ ファイル名が短い(?)場合、ファイルの種類にかかわらず **ファイル名.spc** がファイル名として指定されるようです。

**Comment by dgrfactory** [comment]
@GodGnilda さん
平素よりお世話になっております。
不具合のご報告をいただき、ありがとうございます。

こちらでも不具合を確認いたしました。
タイトルがあればそれをファイル名として採用していましたが、そもそもファイル名に使用できない文字が入ることを想定していない実装となっておりました。
さまざまな考慮や変換を行うよりは、常に SPC ファイル名（拡張子除く）を初期値とするシンプルな仕様に変更いたします。

修正まで、いましばらくお待ちくださいませ。

**Comment by dgrfactory** [comment]
@GodGnilda さん
以下リリースにおいて修正いたしました。
たいへんお手数ですが、ご確認いただきますようお願い申し上げます。
https://github.com/dgrfactory/spcplay/releases/tag/2.19.1.7539

**Comment by GodGnilda** [comment]
@dgrfactory 様

最新版で保存ファイル名の初期値が SPC のファイル名であることを確認いたしました。
ご修正いただきありがとうございます。

**Comment by dgrfactory** [comment]
ご確認いただき、ありがとうございます。
本件、クローズいたします。
