### ISSUE TITLE
[snesapu.dll] scr700lbl に保存される値ではスクリプト領域かデータ領域の判別ができないため予期しないアドレスにジャンプする可能性がある。

### ISSUE THREAD

**Issue by GodGnilda** [dgrfactory/spcplay#43]
平素よりお世話になっております。

スクリプト領域のラベルは
https://github.com/dgrfactory/spcplay/blob/71fe12b35c2738be06191ac85f13cb9c01a98a54/snesapu.dll/APU.asm#L1105-L1114
データ領域のラベルは
https://github.com/dgrfactory/spcplay/blob/71fe12b35c2738be06191ac85f13cb9c01a98a54/snesapu.dll/APU.asm#L2044-L2054
で、それぞれの領域の先頭からの相対アドレスが保存されますが、どちらの領域のラベルか判別不能なため、(意図せずに)データ領域のラベルを使用してジャンプ可能です。

[動作検証スクリプト](https://github.com/GodGnilda/Script700/releases/download/TEST/20220401.7z)

- 20220401_02.700 読み込み直後
![1](https://user-images.githubusercontent.com/72546447/161259360-973cb921-08db-4695-a67c-8f1627c0c4eb.png)
- 20220401_02.700 実行終了時 (Debugger Script700 ウィンドウ : SP の値は誤り・スクリプト領域の命令をマークして前回の PP の値を検索するため最下行スクリプト表示も誤り)
![2](https://user-images.githubusercontent.com/72546447/161259574-c9b6ba57-c900-47f7-b02c-4d19fa64ecfc.png)

**Comment by dgrfactory** [comment]
@GodGnilda さん
お世話になっております。
いつも詳細なご連絡をいただき、ありがとうございます。

こちらでも不具合を確認し、修正版をリリースいたしました。
たいへんお手数ですが、ご確認いただきますようお願い申し上げます。
https://github.com/dgrfactory/spcplay/releases/tag/2.19.2.7666

`bxx` のジャンプ系命令においてデータラベルを指定した場合、改善後はジャンプ動作は行われず（`NOP` と同様に無視され）次の命令が実行されます。
添付いただいたテスト用 .700 で、どちらも `e` が実行され `Ptr=00003` で停止することを確認いたしました。

**Comment by GodGnilda** [comment]
@dgrfactory 様
ジャンプ系命令においてデータラベルを指定した場合に実行されず(SP の値が変化せず)、Ptr の値が $00003 で終了することを確認いたしました。
お忙しいところ、ご対応頂き誠にありがとうございます。

- 20220401_02.700 実行終了時
![20220402](https://user-images.githubusercontent.com/72546447/161380038-f81ecc27-9284-4731-8a74-44f8dc8816e3.png)
