### ISSUE TITLE
SPCs from old Super Mario World hacks started breaking on v2.19.0

### ISSUE THREAD

**Issue by BlinxTheWinx** [dgrfactory/spcplay#44]
Example SPCs: https://www.mediafire.com/file/ug5ixjk7u0usq9g/Old_hacks%2527_SPCs.7z/file

**Comment by dgrfactory** [comment]
Hi, @BlinxTheWinx 
Thank you for reporting the issue.

I tried to play all attached SPC files on the actual device (SHVC-SOUND Unit), but sound is broken as well.
Perhaps, sequence or BRR data is encroaching on echo memory, therefore these data are being broken during playback.

Please read the following FAQ: "My homebrew SPC is not playing properly."
https://github.com/dgrfactory/spcplay/wiki/FAQ#my-homebrew-spc-is-not-playing-properly
