### ISSUE TITLE
Option for GAIN/ADSR to be synchronized with the "Speed" control.

### ISSUE THREAD

**Issue by Pinci19** [dgrfactory/spcplay#45]
Hi! I compose and arrange SNES music and it would be great if there was an option for the envelopes (GAIN/ADSR) to be synchronized with the speed controls, this would be super useful for debugging fast or subtle GAIN changes in a song.

**Comment by dgrfactory** [comment]
Hi, @Pinci19 
Thank you for reporting the new request.

I added "Synchronize Envelope with Speed" option in the "Expansion Flags" settings.
Please download and try the new version to see if it suits your purposes.
https://github.com/dgrfactory/spcplay/releases/tag/2.19.3.7695

**Comment by Pinci19** [comment]
This is exactly what I wanted, thank you!

**Comment by dgrfactory** [comment]
I have fixed a bug that when the playing speed is extremely slow, the envelope update interval also slows down.
https://github.com/dgrfactory/spcplay/releases/tag/2.19.3.7696
