### ISSUE TITLE
Make Old Hexadecimal Numbers Font Can be Choose To Use By User

### ISSUE THREAD

**Issue by monkey03297** [dgrfactory/spcplay#46]
Some people may prefer the old fonts, so I suggest to make it can be config by user.
Maybe the setting can be in spcplay.ini?

**Comment by dgrfactory** [comment]
Hi, @monkey03297
Thank you for reporting the new request.

I added "BMPFONT" settings in the SPCPLAY.INI file.
`BMPFONT  0 : 0` ... Latest font
`BMPFONT  0 : 1` ... Same fonts as v2.19.1 or older

"BMPFONT" is available in build 7707 or later versions.
This is added to SPCPLAY.INI after SPCPLAY.EXE is running and closed once, so change to your liking.
https://github.com/dgrfactory/spcplay/releases/tag/2.19.3.7707

**Comment by monkey03297** [comment]
Thank you for add this settings!
