### ISSUE TITLE
A option to not ignore silent in the first seconds in wav output

### ISSUE THREAD

**Issue by monkey03297** [dgrfactory/spcplay#47]
I am making a oscilloscope view video,
so it is nice to have a option that will not ignore silent in the first seconds in wav output.

**Comment by dgrfactory** [comment]
Hi, @monkey03297 
Thank you for reporting.

Perhaps, the option you want is already exists.
Please try, open SPCPLAY.INI and change value of WAVBLANK to -1.

```
WAVBLANK 0 : -1
```

**Comment by monkey03297** [comment]
Thank you for reply!

Change WAVBLANK to -1 is workinh for me.

I think this issue can be close.
