### ISSUE TITLE
Exporting separate channels timing issue

### ISSUE THREAD

**Issue by Ghettoblaster81** [dgrfactory/spcplay#49]
When i export separate channels, it seems the timing is off.

For instance: Secret of the Forest from Chrono Trigger. When you export channel 1, 2, 3 and 4 separately and merge them back together (in my DAW), the arpeggiator notes are locked on the same grid instead of doing the 4-step arpeggiator. See image attached.

It seems they all start at the exact same beat instead of having the small offset it should need. When i export them as a group, it sounds fine.

In other words: it seems like the start time is off when you export a separate channel (missing the right offset). Maybe it's skipping the silence and goes right to the first sample?

Please advise, thank you.

Hopefully this make it bit more clear what i mean looking at the waveforms in my DAW:

**Wrong render:**

<img width="927" alt="wrong" src="https://user-images.githubusercontent.com/25824665/178943470-fd4ae669-55cd-4c7c-b839-aaca04e22a66.png">
.

**How it should be:**

<img width="899" alt="right" src="https://user-images.githubusercontent.com/25824665/178943465-bdf3962f-4130-42df-a248-73e37b85c37d.png">

**Comment by dgrfactory** [comment]
Hi, @Ghettoblaster81 
Thank you for reporting.

Your report seems to duplicate the content of the following issue.
Please refer to the following issue to see if the problem can be resolved.
See also: https://github.com/dgrfactory/spcplay/issues/47

**Comment by Ghettoblaster81** [comment]
That was the solution! Thank you so much!

**Comment by dakrk** [comment]
With the amount of people reporting this, ideally this should be added as a setting in the GUI
