### ISSUE TITLE
Exporting separate channels using spccmd

### ISSUE THREAD

**Issue by dakrk** [dgrfactory/spcplay#50]
Having to manually click to mute and unmute each channel, and then saving with a different file name to export each channel as its own file can be annoying, so preferably there should be a way in spccmd to easily specify which channels should be played when exporting to WAV with the `-cw` option.
Then to output all channels as it's own file, you could just do a `for /L` from 1 to 8 in CMD.

**Comment by dgrfactory** [comment]
Hi, @dakrk 
Thank you for reporting the new request.

https://github.com/dgrfactory/spcplay/releases/tag/2.19.4.7792
The `-sm` option to switch the channel to be muted separately and the `-gm` option to retrieve the current mute setting have been added to spccmd.
By using the `-sm` option immediately before the `-cw` option, it would be possible to output only the sound of the desired channel.

`-sm` option is used as follows.
```bat
REM Mute only channel 1
spccmd -sm 1

REM Mute channel 1, 2, and 3
spccmd -sm 123

REM Mute all exclude channel 1
spccmd -sm 1 --rev
```

The following batch shows an example of obtaining `output-<ch>.spc`, where each channel is separated from `input.spc`.
```bat
FOR /f "DELIMS=" %%A IN ('spccmd -gm --ch') DO SET MUTE=%%A
FOR %%I IN (1 2 3 4 5 6 7 8) DO (
  spccmd -sm %%I --rev --quiet
  spccmd -cw input.spc output-%%I.wav
)
spccmd -sm %MUTE% --quiet
```

By the way, the first blank adjustment is not performed when even a channel is muted, in other words, the `WAVBLANK` setting in spcplay.ini is ignored now.

**Comment by dakrk** [comment]
It works, thank you!

**Comment by SuperMarioEpicTeam** [comment]
Hey,

Even though this is an old thread, I am interested in performing muted SPC duplicates as you did.
However, spccmd is not yet compiled.

**Comment by dgrfactory** [comment]
Hi, @SuperMarioEpicTeam 

Now, SPCCMD is no longer supported.
If you are using v2.21.0 or newer, you can use SPCPLAY to do the same thing.

The wiki has instructions on how to do this, please refer to it.
https://github.com/dgrfactory/spcplay/wiki/How-to-use-SNES-SPC700-Player#create-a-wav-file

**Comment by SuperMarioEpicTeam** [comment]
Thank you for the reply,

I am actually searching for a method to convert SPC into MIDIs . Since only SPC2MID from Zophar, which blends all the SPC channels into a single MIDI track, is operational, I thought splitting SPCs is the best approach.
