### ISSUE TITLE
Allow seeking when in `Play Time -> Disable/Endless` mode

### ISSUE THREAD

**Issue by LittleEndu** [dgrfactory/spcplay#53]
There should be a seek bar even when in endless mode, the play head should just jump between the start and limit point when looping.

**Comment by dgrfactory** [comment]
Hi, @LittleEndu 
Thank you for reporting the new request.

In the following version, the seek bar is available in endless mode too.
https://github.com/dgrfactory/spcplay/releases/tag/2.19.5.7871
