### ISSUE TITLE
It is possible to save as wave while in `Play Time -> Disable/Endless`

### ISSUE THREAD

**Issue by LittleEndu** [dgrfactory/spcplay#54]
When you try to save as wave when playtime is set to endless, the player freezes.

(I'm using the beta if that's relevant)

**Comment by dgrfactory** [comment]
Hi, @LittleEndu 
Thank you for reporting the issue.

This issue occurred in v2.19.5.7871 and there was a careless mistake, so I released a fixed version.
https://github.com/dgrfactory/spcplay/releases/tag/2.19.5.7878
