### ISSUE TITLE
Exporting as .wav while in endless playback mode ignores ID666 length tags

### ISSUE THREAD

**Issue by Michpem** [dgrfactory/spcplay#56]
Hello! I found a little oddity while exporting .spc files as .wav while having the option for endless playback enabled. Basically, every time I use the .wav export function, I get an audio file that's exactly 2 minutes and 11 seconds (default time?), which doesn't happen when I enable the option for ID666 play time. 

While this barely an issue, it's worth noting that the previous stable release seemed to use the ID666 tags to determine the length of the song before exporting it to .wav, even in endless playback mode.

**Comment by dgrfactory** [comment]
Hi, @Michpem
Thank you for reporting the issue.

As you pointed out, the output time was unintentionally changed when wav output in endless mode.
This issue was fixed in the following release version.
https://github.com/dgrfactory/spcplay/releases/tag/2.19.6.7998

**Comment by dgrfactory** [comment]
https://github.com/dgrfactory/spcplay/releases/tag/2.20.0.8227
