### ISSUE TITLE
Translations 

### ISSUE THREAD

**Issue by monkey03297** [dgrfactory/spcplay#57]
有任何方法可以把程式翻譯成其他語言嗎？
Is there a way that can translate the program to other language?

**Comment by dgrfactory** [comment]
Hi, @monkey03297 

The current version supports only Japanese and English.
Do you imagine something like the Language Pack?
At this time, do not plan to support translations using external files, etc.
For other languages support, the code must be edited directly and re-built.

**Comment by jeffythedragonslayer** [comment]
It would be nice if there was a way to switch the language from the GUI - in the Settings menu.  Many people, such as myself, launch spcplay by double-clicking .SPC files and so didn't notice the spcplay.ini file adjacent to spcplay.exe, which has that setting in it:

`LANGUAGE 1: 0`

**Comment by dgrfactory** [comment]
Hi, @jeffythedragonslayer

Normally, it is not necessary to change the language setting.
Because, automatically switches to English when launched on a non-Japanese Windows OS in the default settings of SPCPLAY.
`LANGUAGE 1 : 0` means language selection automatically.

**Comment by monkey03297** [comment]
> Hi, @monkey03297
> 
> The current version supports only Japanese and English. Do you imagine something like the Language Pack? At this time, do not plan to support translations using external files, etc. For other languages support, the code must be edited directly and re-built.

I see.
Thank you for respond!
