### ISSUE TITLE
[Request] Add toggleable dark theme

### ISSUE THREAD

**Issue by exodustx0** [dgrfactory/spcplay#58]
I've noticed that spcplay has a define `WIN10DARK` that's commented out. I have not seen what spcplay in a dark theme looks like, as I'm unable to build the executable, but having a dark theme available would be very welcome. Can this feature be uncommented and exposed as a toggleable setting?

**Comment by dgrfactory** [comment]
Hi, @exodustx0

Thank you for reporting the new request.

`WIN10DARK` is still under experimentation.
When `WIN10DARK` is enabled, the display changes to the following:
![20230806-001](https://github.com/dgrfactory/spcplay/assets/46675013/d63428ed-881a-4fe8-a7bf-6123c7704c37)

As you can see, only open menus (and title bar) are darkened.
It is not ready for full dark mode yet.

SNES SPC700 Player is a legacy Win32 desktop application.
Windows 10/11 supports dark mode by default for applications created with newer frameworks, but does not for legacy (win32 API).
My hope is that with just a few Win32 API calls will display in full dark mode.

**Comment by exodustx0** [comment]
Ah, figures that it's work-in-progress. Thanks for the info!

**Comment by dgrfactory** [comment]
Hi, @exodustx0
Thank you for waiting so long.

Although it is still an experiment, I have released a version that supports dark theme.
https://github.com/dgrfactory/spcplay/releases/tag/2.20.3.8408b
After opening SPCPLAY.EXE and closing, please setting `THEME` to `1` in SPCPLAY.INI and try starting SPCPLAY again.

![SNES SPC700 Player](https://dgrfactory.jp/img/spcplay-004.png)
