### ISSUE TITLE
Exporting as wav files skips the salience 

### ISSUE THREAD

**Issue by HUNTINGTHIEVES** [dgrfactory/spcplay#60]
when you export the audio channel as a .wav all audio channels will skip the silence and it causes all the audio channel samples to be out of sync. if possible could the author fix the time skip when converting a audio channel to .wav

**Comment by dgrfactory** [comment]
Hi, @HUNTINGTHIEVES 
Thank you for reporting.

Is this the same question as the following issue? -> https://github.com/dgrfactory/spcplay/issues/47 , https://github.com/dgrfactory/spcplay/issues/49
