### ISSUE TITLE
Music fades out towards end of song when converted to wav file

### ISSUE THREAD

**Issue by HUNTINGTHIEVES** [dgrfactory/spcplay#62]
When I convert a file to wav it will add a fade out towards the end of the song and not loop. Would anyone know how to fix this if possible.

**Comment by dgrfactory** [comment]
Hi, @HUNTINGTHIEVES 

Is your question that a WAVE file is created with an unintentionally short length?
The SPC file has tag information named ID666, and the playing time and fade-out time are saved.
This tag information is referenced during WAVE output too.
