### ISSUE TITLE
Just a question: What's the "old Sound Blaster card" in pitch settings?

### ISSUE THREAD

**Issue by brickblock369** [dgrfactory/spcplay#63]
In the pitch settings I can find "Old Sound Blaster Card". How was it used in SNES music in the first place?
Was SPCPlay originally made for IBM PCs as well?

**Comment by dgrfactory** [comment]
Hi, @brickblock369 

"Old Sound Blaster Card" option already existed in original SNESAPU before forking.
There was a time when SNESAPU was used in SPC700 emulation of snes9x, and it seems that it was prepared at that time.
I don't know much about how it is used, it seems that the old Sound Blaster sometimes occurred noise at 32,000Hz but played correctly at 31,800Hz, so it may have been intended to compensate for pitch changes.

Development of spcplay v2 began about 20 years ago on computers with IBM PC/AT compatible architecture.
