### ISSUE TITLE
Disable pitch overflow.

### ISSUE THREAD

**Issue by Pinci19** [dgrfactory/spcplay#64]
Hello! This is a (seemingly) small feature request; I was thinking that it would be interesting to have an option to disable pitch overflow, by this I mean let pitch go beyond 3FFF instead of looping back.

**Comment by dgrfactory** [comment]
Hi, @Pinci19
Thank you for reporting the new request.

I added "Disable Pitch Limit" option in the "Expansion Flags" settings.
Please download and try the new version.
https://github.com/dgrfactory/spcplay/releases/tag/2.20.0.8200

If this option flag to ON, changes the pitch limit from 0x3FFF to 0xFFFF.

**Comment by Pinci19** [comment]
This works as expected. Thank you so much!

**Comment by dgrfactory** [comment]
https://github.com/dgrfactory/spcplay/releases/tag/2.20.0.8227
