### ISSUE TITLE
[Request] SNESAPU.dll 64bit support

### ISSUE THREAD

**Issue by CrispulentCrisps** [dgrfactory/spcplay#65]
Hello, I am wanting to use the SNESAPU.dll from this github in a SNES-based music tracker, but have found that the file itself is 32bit, while my program is in 64 bits and can only compile to that version.

I was wondering if it would be possible to extend the dll to support 64 bit, helping it stand for use in programs without 32bit equivalents.

If not I understand that it can be difficult work.

**Comment by dgrfactory** [comment]
Hi, @CrispulentCrisps 
Thank you for reporting the new request.

Almost all of the code in SNESAPU is written in i386 assembler, and more than half of it will have to be rewritten to support x64.
Therefore, there are currently no plans to support x64.

If you're looking for a SHVC-SOUND emulator that supports x64, how would you like to use one written in C from the beginning, such as bsnes/snes9x?
These provide a more accurate emulation than SNESAPU.

https://github.com/bsnes-emu/bsnes/tree/master/bsnes/processor/spc700
https://github.com/bsnes-emu/bsnes/tree/master/bsnes/sfc/dsp
https://github.com/snes9xgit/snes9x/tree/master/apu

**Comment by CrispulentCrisps** [comment]
> Almost all of the code in SNESAPU is written in i386 assembler, and more than half of it will have to be rewritten to support x64. Therefore, there are currently no plans to support x64.

aye I understand that is a major task, and I can see why you'd be quite averse to it.

Thank you for the C based SPC emulation files. will hope this serves well for my program's future!

**Comment by dgrfactory** [comment]
@CrispulentCrisps 
I hope the wonderful program you have planned is successfully completed.
