### ISSUE TITLE
[Request] Add a confirmation pop up when pressing Clear

### ISSUE THREAD

**Issue by Michpem** [dgrfactory/spcplay#66]
Hello! I have a small feature suggestion. Would it be possible to add a small pop up window asking for confirmation when the Clear button is pressed? I accidentally clicked on it the other day and wiped out my SPC playlist, haha. Thankfully, I had a backup .lst file so nothing was lost, but having a confirmation dialog in case accidents like these happen would be nice. Perhaps something like this:

"Are you sure you want to clear your playlist? This action cannot be reversed.
[Yes] [Cancel]"

This is a very small request, so feel free to prioritize any potential updates you may have planned instead of this!

**Comment by dgrfactory** [comment]
Hi, @Michpem

Thank you for reporting the new request.
And, I am sorry to trouble you.

In the following releases, a confirmation dialog has been added when clearing a playlist.
I used the sample message you sent as is, thanks!
https://github.com/dgrfactory/spcplay/releases/tag/2.20.3.8412b

**Comment by Michpem** [comment]
No trouble at all! And thank you very much for adding this so quickly!
