### ISSUE TITLE
Spc700 player not opening.

### ISSUE THREAD

**Issue by minecraft619** [dgrfactory/spcplay#67]
I don't know why this program won't open. I open the program. It loads then nothing happens.
I have a windows 11. Tried doing the compatibility stuff and still does not work.

**Comment by dgrfactory** [comment]
Hi, @minecraft619 

> It loads then nothing happens.

Will the window or message dialog not even be displayed?

When you open spcplay.exe after opening Task Manager, is "SNES SPC700 Player" present in "Apps"?
If it doesn't appear or disappears quickly, try the following:

1. Place spcplay.exe and snesapu.dll in a simple path. (e.g. `C:\spcplay`)
2. After deleting spcplay.ini, start spcplay.exe.
3. Restart Windows and start spcplay.exe again.

**Comment by minecraft619** [comment]
Worked
