### ISSUE TITLE
SPC Timer resets after 476 seconds

### ISSUE THREAD

**Issue by Argonfunk** [dgrfactory/spcplay#70]
Rendered with SPCPlay v2.20.5 (build 8581) on Windows 10
https://github.com/user-attachments/assets/839b5548-c134-427a-88b7-8a1d96461c24

Whenever an item reaches 7:56 (476 seconds) on playback, the SPC Timer is reset to draw from the very beginning which is an inaccurate visualization since the fadeout timer and playback timers are counted for properly. This occurs with every SPC file across several different sound drivers that are longer than 476 seconds on ID666 Time.

**Comment by dgrfactory** [comment]
Hi, @Argonfunk 
Thank you for reporting the issue.

This issue has been fixed in the following release:
https://github.com/dgrfactory/spcplay/releases/tag/2.20.6.8652b
An overflow occurred during the numerical calculation because variable is 32-bit, so it has been expanded to 64-bit.
